### ISSUE TITLE
unhandledRejection with no results

### ISSUE THREAD

**Issue by au5ton** [au5ton/Roboruri#52]
[2018/1/13 @ 17:17:47] Summon: {Myriad Colors Phantom World}
⚠️  [2018/1/13 @ 17:17:47] cache empty: nothing cached for this query
⚠️  [2018/1/13 @ 17:17:47] database empty: couldn't find that name in the database
[2018/1/13 @ 17:17:47] search: {Myriad Colors Phantom World} => Myriad Colors Phantom World
execution time: 428.883ms
    [2018/1/13 @ 17:18:4] kitsu error caught
    🚫  [2018/1/13 @ 17:18:4] DataSource.KITSU error caught: undefined
⚠️  [2018/1/13 @ 17:18:4] mal returned no results
⚠️  [2018/1/13 @ 17:18:4] anilist returned no results
🚫  [2018/1/13 @ 17:18:4] failed to search with Searcher: insufficient results, has no results to offer
🚫  [2018/1/13 @ 17:18:4] unhandledRejection: TypeError: Cannot set property 'status' of undefined
    at Searcher.searchAnimes.then.catch (/mnt/mpathb/au5ton/sandbox/Roboruri/bot.js:471:45)
TypeError: Cannot set property 'status' of undefined
    at Searcher.searchAnimes.then.catch (/mnt/mpathb/au5ton/sandbox/Roboruri/bot.js:471:45)

**Comment by au5ton** [comment]
retried this, probably occurred because the anime databases were incomplete and roboruri didn't know how to react.

**Comment by au5ton** [comment]
retried this again and it still works great. closing this issue.
